version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  groups:
    nestjs:
      patterns:
        - "@nestjs*"
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: devcontainers
  directory: "/.devcontainer"
  schedule:
    interval: weekly
