name: Bump version (cron)

on:
  schedule:
    - cron: "15 3 * * TUE"

jobs:
  scheduled_bump:
    permissions:
      contents: write
    uses: ./.github/workflows/bump.yml
    secrets: inherit
    with:
      semver: minor
